apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1USXhOVEUzTlRFME1sb1hEVE14TVRJeE16RTNOVEUwTWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGxSCjFQSHlEaGNoenRWUlJWVVZIQ05SS01IWlp6QmhtRFkwRzVON09KTVdkQjd0cjB3bElISU5wNUsra3I4YkZid2cKWDliMGRKdVdlOGphMm5XSkpWZmpmOWNCOTlPQXpoOVQ4cXl6TEdjZzJ1RDVjRDZWT1lvRHNqc0xRMGRoWnpBcwpZUjBka1lyQUNnUDA0ZWpOS0Y3WW5VaHlQUkp3YmdXUkp5blRBZVlGU3J1MjlnRnJ3Nm9NamdvVGtmK1M2U0RZCjFxQnlPc3BYaXRoaHVvSk1BU1V3U1V5bjhtdEZNUi9UcWNZMWFDNncrTDJzazJ2V3dyeGx1SFgrZ2FiRWtvRVoKOHBMM0cwTlJjVS8zZ1hlVmVkN3dySXgvREhrdHNLSlJsMlNBZTBieGo1ZUhNUksrVE40ME5hZFRNRytCdlRveQpUMkRBQkVSVDZHUkVidkFYVWRjQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZNZTNmNGdzL1VGY0loNk5SK0EyT2tYMjRITmtNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBVFNtRG9xbXZTY0VQS0dHRHhNRTJac3lidXpFWXl5ZmQrOGJuN1VyYTF1Q2gvYmJNYQpIMFFXQVF4Y2libUpPdHVGS1FVZUNhNVVmb1FabHlIZHEvQ0FZQVJIRFM2TzFyQVZ0RWlpYWlXN1g0Smc1QjlCCmJUSjNWYndHdDhkK1dLUk5lYlZUZ01MVUk2NExzRllub2hHd2QyZjNVc2FiRFFkK1ZLVnhLdUVKQ0lGaGkzVFcKWlNUT0xjTDErSk9RbHNLOHY2Z3JFK0hsTHNhZlVKNlloOWljeVI2S1BkcWFwaUptQmlBa0hWbU14Y3hwTlNlYwp0ZVZDOHdIekRvdEYvMmJienBGVkZ6UXd2R3JWaUNZdjJzdStkN2Y0UGNvL0JlWVFtTVh1WFlsMUFWbGROd1pOCi9zbFQ4ZjV3WUxNNlUycVNXZU8vemtOazhDdVc3R21Jd3hLOQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://45212E96DC921B1173198122A8D82B7E.gr7.us-east-1.eks.amazonaws.com
  name: pipeline.us-east-1.eksctl.io
contexts:
- context:
    cluster: pipeline.us-east-1.eksctl.io
    user: xKALiber.user@pipeline.us-east-1.eksctl.io
  name: xKALiber.user@pipeline.us-east-1.eksctl.io
current-context: xKALiber.user@pipeline.us-east-1.eksctl.io
kind: Config
preferences: {}
users:
- name: xKALiber.user@pipeline.us-east-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - eks
      - get-token
      - --cluster-name
      - pipeline
      - --region
      - us-east-1
      command: aws
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      provideClusterInfo: false